;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="burnRequest",DevComment="BP")
+GameplayTagList=(Tag="myDuration",DevComment="")
+GameplayTagList=(Tag="myMagnitude",DevComment="")
+GameplayTagList=(Tag="UCombatantManager_burnEffect",DevComment="C++")
+GameplayTagList=(Tag="UCombatantManager_burnEffect_duration",DevComment="C++")
+GameplayTagList=(Tag="UCombatantManager_burnEffect_magnitude",DevComment="C++")
+GameplayTagList=(Tag="UCombatantManager_damageEffect_magnitude",DevComment="C++")

